export const DEMO_SCREEN_NAMES = [
  "activity",
  "ask/index",
  "ask/place",
  "ask/options",
  "ask/compile",
  "ask/status",
  "ask/rejected",
  "ask/vendor",
  "ask/answer/[id]",
  "observe/index",
  "observe/task/[id]",
  "observe/approach",
  "observe/capture",
  "observe/evidence",
  "observe/verifying",
  "observe/earned",
  "live/index",
  "live/new",
  "live/[id]",
] as const;
