import { CommunitySpotDetails } from "@/components/CommunitySpotDetails";
import { StyleSheet, Text, View } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { AppScreen, MissingDataState, PrimaryButton, ScreenHeader } from '@/components/ui';
import { MapSurface, detailRegion } from '@/components/MapSurface';
import { useYonderStore } from '@/lib/store';
import { observe, font, type } from '@/lib/theme';
import { money } from '@/lib/pricing';

export default function TaskScreen() {
  const {id} = useLocalSearchParams<{id:string}>(); const router = useRouter(); const query = useYonderStore(s=>s.queries.find(q=>q.id===id)); const place = useYonderStore(s=>s.places.find(p=>p.id===query?.placeId));
  if (!query || !place || ['ANSWERED','REFUNDED','BLOCKED'].includes(query.state)) return <MissingDataState title="This check is no longer available."/>;
  const start = (mode:'demo'|'device') => { if (place.communitySpot && mode === 'demo') return; const state=useYonderStore.getState();state.setActiveTask(query.id);state.setCaptureMode(mode);state.acceptActiveTask();router.push('/observe/approach'); };
  return <AppScreen><ScreenHeader eyebrow="A PAIR OF EYES, PLEASE"/><CommunitySpotDetails place={place}/><View style={styles.map}><MapSurface mode="observe" style={StyleSheet.absoluteFill} initialRegion={detailRegion({latitude:place.lat,longitude:place.lng})} markers={[{id:place.id,label:place.name,coordinate:{latitude:place.lat,longitude:place.lng}}]} geofence={{center:{latitude:place.lat,longitude:place.lng},radius:place.geofenceM}}/></View><Text style={styles.place}>{place.name}</Text><Text accessibilityRole="header" style={styles.title}>{query.question}</Text><View style={styles.card}><Text style={styles.label}>WHAT TO LOOK FOR</Text>{query.spec.slice(0,3).map((item,i)=><Text key={i} style={styles.body}>{String(i+1).padStart(2,'0')}  {item}</Text>)}</View><Text style={styles.reward}>{money(query.observerRewardCents)} <Text style={styles.body}>simulated reward</Text></Text><Text style={styles.body}>Only film where you’re allowed. Keep people’s faces and private information out of frame. Stop if asked.</Text><View style={styles.actions}>{!place.communitySpot && <PrimaryButton label="Explore an example" onPress={()=>start('demo')}/>}<PrimaryButton label="I’m there · use GPS & camera" variant="secondary" onPress={()=>start('device')}/><Text style={styles.note}>Device checks use real location readings. Evidence stays on this device and cannot earn a payout yet.</Text></View></AppScreen>;
}
const styles=StyleSheet.create({map:{height:220,borderRadius:16,overflow:'hidden'},place:{...type.label,color:observe.inkSoft,marginTop:22},title:{fontFamily:font.ui600,fontSize:32,lineHeight:37,letterSpacing:-1,color:observe.ink,marginTop:10},card:{borderRadius:16,backgroundColor:observe.surface,padding:22,gap:14,marginVertical:22},label:{...type.micro,color:observe.accent},body:{...type.body,fontSize:14,lineHeight:23,color:observe.inkSoft},reward:{fontFamily:font.mono500,fontSize:34,color:observe.accent,marginBottom:16},actions:{gap:12,marginTop:24},note:{...type.label,fontSize:11,lineHeight:18,color:observe.inkSoft,textAlign:'center'}});
